name: backend

on:
  push:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: myapp/backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: myapp/backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: myapp/backend/dist/index.js
          retention-days: 5
