name: backend

on:
  push:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
      - users: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test
      - run: npm run build
